/**
 * src/ui/codex.ts — the CODEX reference screen. OWNER: Gameplay Engineer
 * (content/codex/ + this screen, brief c1-codex-screen; GDD §2.10).
 *
 * The optional main-menu reference a player consults voluntarily — "never a gate
 * before play" (GDD §2.10, verbatim). Four tabs (BOTS / SHIPS / SYSTEMS /
 * STRATEGY) over the four `content/codex/*.json` files: a scrollable list of
 * entry titles on the left, the selected entry's detail on the right — its
 * summary, its body, the machine-checked `facts[]` (the numbers
 * `tests/codex/codex-constants.test.ts` pins to `src/sim/constants.ts`), any
 * difficulty/hull badges, and its cross-references. A BACK button leaves.
 *
 * Same three-piece discipline as every screen in this directory: a pure, DOM-free
 * model with its layout co-located, plus a thin Pixi view ({@link ./codex-view})
 * that draws exactly what this returns and decides nothing. Nothing here imports
 * PixiJS, so the whole screen unit-tests headless.
 *
 * **The data is handed in, not imported.** `content/codex/` lives outside `src/`
 * (it is regenerated by the codex pipeline, not compiled), so the model takes the
 * four parsed files as a value — `createCodex(normalizeCodex(files))` — exactly
 * as `lobbyModel` takes a `LobbyState`. Whoever boots the client
 * (`src/main.ts`) imports the JSON (Vite resolves it) and hands it over; the
 * tests load it off disk with `readFileSync`. So this file never reaches across
 * the compile boundary, and a malformed entry is normalised away here rather than
 * crashing a draw.
 *
 * **Scrolling lives in the view, not the model.** The entry rail (SYSTEMS has
 * fourteen entries) and a long body both scroll vertically; that offset is view
 * state. The one place the model must know about it is the hit test — a tap on a
 * scrolled rail lands on a different entry — so {@link codexHitTest} takes the
 * rail's scroll offset as a scalar and keeps the entry geometry pure and here,
 * rather than leaking it into the view.
 */

import type { Rect, Viewport } from '@platform/layout-registry';
import { MENU_ROW_GAP, hitRect, menuContent } from './menu-geometry';
import type { Insets } from './menu-geometry';

// ---------------------------------------------------------------------------
// The four tabs
// ---------------------------------------------------------------------------

/** The four codex files, which are the four tabs, in screen order. */
export type CodexCategory = 'bots' | 'ships' | 'systems' | 'strategy';

/** One tab's identity. The layout, the view and the hit test all walk this same
 *  list, so a re-ordered tab strip can never mis-route a tap. */
export interface CodexTab {
  readonly id: CodexCategory;
  readonly label: string;
}

/** The tabs, left to right — the BOTS / SHIPS / SYSTEMS / STRATEGY the brief
 *  names, mapped one-to-one to the four `content/codex/codex-*.json` files. */
export const CODEX_TABS: readonly CodexTab[] = [
  { id: 'bots', label: 'BOTS' },
  { id: 'ships', label: 'SHIPS' },
  { id: 'systems', label: 'SYSTEMS' },
  { id: 'strategy', label: 'STRATEGY' },
];

/** The screen's one heading, in Audiowide. */
export const CODEX_TITLE = 'CODEX';
/** The back control's label. */
export const CODEX_BACK_LABEL = 'BACK';

// ---------------------------------------------------------------------------
// The data — the parsed codex files, normalised into one typed shape
// ---------------------------------------------------------------------------

/** One machine-checked number from an entry's `facts[]`. `value` is the codex's
 *  claim; `unit` is its human unit ("HP", "s") or null for a bare count. The
 *  constant pointer that pins it to the sim is the pipeline's concern
 *  (`tests/codex/codex-constants.test.ts`), not the screen's, so it is dropped. */
export interface CodexFact {
  readonly label: string;
  readonly value: number;
  readonly unit: string | null;
}

/** One codex entry, normalised. Only the fields the screen draws survive the
 *  parse; `tags`, `category` and the fact `constant` pointers are pipeline
 *  metadata and are dropped here. */
export interface CodexEntry {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly body: string;
  readonly facts: readonly CodexFact[];
  readonly seeAlso: readonly string[];
  /** A bot's difficulty tier ("Easy" / "Standard" / "Hard"), or null off the
   *  BOTS tab (and on the bots overview, which is nobody in particular). */
  readonly difficulty: string | null;
  /** A bot's hull, by lobby name, or null where the entry is not a single ship. */
  readonly hull: string | null;
}

/** One tab's worth of content: the file's title and its entries, in file order. */
export interface CodexSection {
  readonly category: CodexCategory;
  readonly title: string;
  readonly entries: readonly CodexEntry[];
}

/** All four sections, keyed by tab. Every tab is always present (an empty section
 *  for a file that failed to parse), so the screen never has to guard a tab. */
export type CodexData = Readonly<Record<CodexCategory, CodexSection>>;

/** The four parsed files, as `JSON.parse`/Vite hands them over — each `unknown`
 *  because a JSON import is not a typed thing until this module has vetted it. */
export type CodexRaw = Partial<Record<CodexCategory, unknown>>;

// --- Defensive coercion ----------------------------------------------------
//
// A codex file is player-facing fiction regenerated by a separate pipeline; a
// stray shape must never reach a draw as an `undefined.length`. Everything below
// coerces rather than trusts, and drops an entry that has no id/title/body — the
// three fields without which there is nothing to show.

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

function asStringOrNull(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

function asStringArray(value: unknown): readonly string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((v): v is string => typeof v === 'string');
}

function asFacts(value: unknown): readonly CodexFact[] {
  if (!Array.isArray(value)) return [];
  const facts: CodexFact[] = [];
  for (const raw of value) {
    if (raw === null || typeof raw !== 'object') continue;
    const f = raw as Record<string, unknown>;
    if (typeof f.value !== 'number') continue;
    facts.push({ label: asString(f.label), value: f.value, unit: asStringOrNull(f.unit) });
  }
  return facts;
}

function normalizeEntry(value: unknown): CodexEntry | null {
  if (value === null || typeof value !== 'object') return null;
  const e = value as Record<string, unknown>;
  const id = asString(e.id);
  const title = asString(e.title);
  const body = asString(e.body);
  if (id === '' || title === '' || body === '') return null;
  return {
    id,
    title,
    summary: asString(e.summary),
    body,
    facts: asFacts(e.facts),
    seeAlso: asStringArray(e.see_also),
    difficulty: asStringOrNull(e.difficulty),
    hull: asStringOrNull(e.hull),
  };
}

function normalizeSection(category: CodexCategory, value: unknown): CodexSection {
  const file = value !== null && typeof value === 'object' ? (value as Record<string, unknown>) : {};
  const rawEntries = Array.isArray(file.entries) ? file.entries : [];
  const entries: CodexEntry[] = [];
  for (const raw of rawEntries) {
    const entry = normalizeEntry(raw);
    if (entry) entries.push(entry);
  }
  return { category, title: asString(file.title), entries };
}

/** Vet the four parsed files into one typed {@link CodexData}. Total: a missing
 *  or malformed file becomes an empty section, and a malformed entry is dropped,
 *  so the screen is handed something it can always draw. */
export function normalizeCodex(raw: CodexRaw): CodexData {
  return {
    bots: normalizeSection('bots', raw.bots),
    ships: normalizeSection('ships', raw.ships),
    systems: normalizeSection('systems', raw.systems),
    strategy: normalizeSection('strategy', raw.strategy),
  };
}

// ---------------------------------------------------------------------------
// The state
// ---------------------------------------------------------------------------

/** The whole screen, as one immutable value: the data, which tab is live, and
 *  which entry within it is selected (null only when a tab is empty). */
export interface CodexState {
  readonly data: CodexData;
  readonly activeTab: CodexCategory;
  readonly selectedId: string | null;
}

/** Open the codex on `tab` (BOTS by default), its first entry selected. */
export function createCodex(data: CodexData, tab: CodexCategory = 'bots'): CodexState {
  return { data, activeTab: tab, selectedId: firstId(data[tab]) };
}

function firstId(section: CodexSection): string | null {
  return section.entries[0]?.id ?? null;
}

/**
 * Switch tabs, selecting the new tab's first entry. Identity-stable on a no-op
 * (tapping the live tab returns the same object) — the same stillness discipline
 * {@link ./lobby-flow} `withLobby` keeps, so a re-tap churns no state.
 */
export function selectCodexTab(state: CodexState, tab: CodexCategory): CodexState {
  if (tab === state.activeTab) return state;
  return { ...state, activeTab: tab, selectedId: firstId(state.data[tab]) };
}

/**
 * Select the entry at `index` within the active tab. Out-of-range indices and a
 * re-select of the live entry are no-ops that return the same object.
 */
export function selectCodexEntry(state: CodexState, index: number): CodexState {
  const entry = state.data[state.activeTab].entries[index];
  if (!entry || entry.id === state.selectedId) return state;
  return { ...state, selectedId: entry.id };
}

/** The entries of the active tab, in order — the list the rail draws. */
export function activeEntries(state: CodexState): readonly CodexEntry[] {
  return state.data[state.activeTab].entries;
}

/** The selected entry, or the tab's first as a fallback (a non-null selection
 *  that fell out of the data), or null for an empty tab. */
export function activeEntry(state: CodexState): CodexEntry | null {
  const entries = activeEntries(state);
  return entries.find((e) => e.id === state.selectedId) ?? entries[0] ?? null;
}

/** The selected entry's index in the active tab, or -1. */
export function activeEntryIndex(state: CodexState): number {
  return activeEntries(state).findIndex((e) => e.id === state.selectedId);
}

// ---------------------------------------------------------------------------
// The per-frame model
// ---------------------------------------------------------------------------

/** One tab as the strip draws it. */
export interface CodexTabView {
  readonly label: string;
  readonly active: boolean;
}

/** One entry title as the rail draws it. */
export interface CodexEntryView {
  readonly title: string;
  readonly selected: boolean;
}

/** A rendered fact line — the value and unit already formatted ("15 HP"). */
export interface CodexFactView {
  readonly label: string;
  readonly value: string;
}

/** The detail pane for the selected entry. */
export interface CodexDetailView {
  readonly title: string;
  readonly summary: string;
  /** Difficulty / hull chips, in that order, present only when the entry has
   *  them (a bot). Empty for a systems or strategy entry. */
  readonly badges: readonly string[];
  readonly body: string;
  readonly facts: readonly CodexFactView[];
  readonly seeAlso: readonly string[];
}

/** The codex for one frame. The view draws exactly this. */
export interface CodexModel {
  readonly title: string;
  readonly backLabel: string;
  readonly sectionTitle: string;
  readonly tabs: readonly CodexTabView[];
  readonly entries: readonly CodexEntryView[];
  readonly detail: CodexDetailView | null;
}

/** Format a fact's value and unit for display: "15 HP", "10 s", or a bare "8". */
export function formatFactValue(fact: CodexFact): string {
  return fact.unit ? `${fact.value} ${fact.unit}` : `${fact.value}`;
}

/** Resolve `see_also` entry ids to their human titles, across every tab (a bot
 *  cross-links to a ship), dropping any id that names no entry. So the footer
 *  reads "Beta", never the raw "b2". */
function resolveSeeAlso(data: CodexData, ids: readonly string[]): readonly string[] {
  const titles: string[] = [];
  for (const id of ids) {
    for (const tab of CODEX_TABS) {
      const found = data[tab.id].entries.find((e) => e.id === id);
      if (found) {
        titles.push(found.title);
        break;
      }
    }
  }
  return titles;
}

function detailFor(entry: CodexEntry | null, data: CodexData): CodexDetailView | null {
  if (!entry) return null;
  const badges: string[] = [];
  if (entry.difficulty) badges.push(entry.difficulty);
  if (entry.hull) badges.push(entry.hull);
  return {
    title: entry.title,
    summary: entry.summary,
    badges,
    body: entry.body,
    facts: entry.facts.map((f) => ({ label: f.label, value: formatFactValue(f) })),
    seeAlso: resolveSeeAlso(data, entry.seeAlso),
  };
}

/** Build the frame model. Pure: the view draws exactly this and decides nothing. */
export function codexModel(state: CodexState): CodexModel {
  const selected = activeEntry(state);
  return {
    title: CODEX_TITLE,
    backLabel: CODEX_BACK_LABEL,
    sectionTitle: state.data[state.activeTab].title,
    tabs: CODEX_TABS.map((t) => ({ label: t.label, active: t.id === state.activeTab })),
    entries: activeEntries(state).map((e) => ({ title: e.title, selected: e.id === selected?.id })),
    detail: detailFor(selected, state.data),
  };
}

// ---------------------------------------------------------------------------
// Layout
// ---------------------------------------------------------------------------

/** Gap between rail entries. */
export const CODEX_ENTRY_GAP = 6;

/** The title/back band off the top of the content box. */
export const CODEX_TITLE_HEIGHT = 48;
/** The tab strip height (desktop pointer)… */
export const CODEX_TAB_HEIGHT = 44;
/** …and a fatter strip under a thumb. */
export const CODEX_TAB_HEIGHT_TOUCH = 52;
/** One entry row in the rail (desktop)… */
export const CODEX_ENTRY_HEIGHT = 40;
/** …and under a thumb. */
export const CODEX_ENTRY_HEIGHT_TOUCH = 48;
/** The back button's width, capped so it never eats the title. */
export const CODEX_BACK_WIDTH = 120;
/** The entry rail's width band. */
export const CODEX_RAIL_MIN = 132;
export const CODEX_RAIL_MAX = 260;
/** Fraction of the content width the rail asks for before the min/max clamp. */
export const CODEX_RAIL_FRACTION = 0.34;

export interface CodexLayoutOptions {
  readonly isTouch?: boolean;
  readonly insets?: Insets;
}

/**
 * The codex's rects. `railEntries` are the *unscrolled* positions of every entry
 * in the active tab, stacked from the top of `rail`; the view clips them to
 * `rail` and scrolls them, and {@link codexHitTest} shifts them by the same
 * offset. `detail` is the whole right pane; the body's own scroll is the view's.
 */
export interface CodexLayout {
  readonly content: Rect;
  readonly title: Rect;
  readonly back: Rect;
  readonly tabs: readonly Rect[];
  readonly rail: Rect;
  readonly railEntries: readonly Rect[];
  readonly detail: Rect;
  readonly entryHeight: number;
  readonly isTouch: boolean;
}

/**
 * Lay the screen out for a viewport. Because a portrait phone is landscape-locked
 * (see `src/main.ts`), the logical viewport is always wide-and-short, so the rail
 * and detail sit side by side rather than stacking — the short height is what the
 * rail and body scroll to absorb.
 *
 * @param entryCount how many entries the active tab has — the rail lays out one
 *   rect per entry (the view scrolls the overflow).
 */
export function codexLayout(
  viewport: Viewport,
  entryCount: number,
  options: CodexLayoutOptions = {},
): CodexLayout {
  const isTouch = options.isTouch ?? false;
  const content = menuContent(viewport, options.insets);

  const titleHeight = Math.min(CODEX_TITLE_HEIGHT, content.height);
  const title: Rect = { x: content.x, y: content.y, width: content.width, height: titleHeight };
  const backWidth = Math.min(CODEX_BACK_WIDTH, content.width);
  const back: Rect = {
    x: content.x + content.width - backWidth,
    y: title.y,
    width: backWidth,
    height: titleHeight,
  };

  const tabHeight = Math.min(isTouch ? CODEX_TAB_HEIGHT_TOUCH : CODEX_TAB_HEIGHT, Math.max(0, content.height - titleHeight));
  const tabTop = title.y + titleHeight + MENU_ROW_GAP;
  const tabs = tabStrip({ x: content.x, y: tabTop, width: content.width, height: tabHeight });

  const bodyTop = tabTop + tabHeight + MENU_ROW_GAP;
  const bodyHeight = Math.max(0, content.y + content.height - bodyTop);

  const railWidth = clampRailWidth(content.width);
  const rail: Rect = { x: content.x, y: bodyTop, width: railWidth, height: bodyHeight };
  const detailX = rail.x + railWidth + MENU_ROW_GAP;
  const detail: Rect = {
    x: detailX,
    y: bodyTop,
    width: Math.max(0, content.x + content.width - detailX),
    height: bodyHeight,
  };

  const entryHeight = isTouch ? CODEX_ENTRY_HEIGHT_TOUCH : CODEX_ENTRY_HEIGHT;
  const railEntries: Rect[] = [];
  for (let i = 0; i < Math.max(0, entryCount); i++) {
    railEntries.push({
      x: rail.x,
      y: rail.y + i * (entryHeight + CODEX_ENTRY_GAP),
      width: rail.width,
      height: entryHeight,
    });
  }

  return { content, title, back, tabs, rail, railEntries, detail, entryHeight, isTouch };
}

function clampRailWidth(contentWidth: number): number {
  const asked = contentWidth * CODEX_RAIL_FRACTION;
  const capped = Math.min(CODEX_RAIL_MAX, Math.max(CODEX_RAIL_MIN, asked));
  // Never let the rail crowd out the detail on a genuinely tiny viewport: at most
  // half the content, so both panes always have a share.
  return Math.min(capped, contentWidth / 2);
}

/** Four equal tabs across `band`, gap-separated, in {@link CODEX_TABS} order. */
function tabStrip(band: Rect): Rect[] {
  const n = CODEX_TABS.length;
  const gap = MENU_ROW_GAP;
  const width = Math.max(0, (band.width - (n - 1) * gap) / n);
  const rects: Rect[] = [];
  for (let i = 0; i < n; i++) {
    rects.push({ x: band.x + i * (width + gap), y: band.y, width, height: band.height });
  }
  return rects;
}

/** The total height every entry would occupy if the rail did not scroll — the
 *  view clamps its scroll offset to `max(0, this - rail.height)`. */
export function codexRailContentHeight(layout: CodexLayout): number {
  const n = layout.railEntries.length;
  if (n === 0) return 0;
  return n * layout.entryHeight + (n - 1) * CODEX_ENTRY_GAP;
}

// ---------------------------------------------------------------------------
// Hit test
// ---------------------------------------------------------------------------

/** What a tap on the codex resolves to. */
export type CodexTarget =
  | { readonly kind: 'back' }
  | { readonly kind: 'tab'; readonly index: number }
  | { readonly kind: 'entry'; readonly index: number };

/**
 * The target a tap at `(x, y)` hits, or null. `railScroll` is how far the entry
 * rail has been scrolled down (view state, default 0): each entry's on-screen
 * rect is its layout rect shifted up by that offset, and a hit only counts if it
 * also falls inside the rail's clip rect — a title scrolled out of view is not
 * tappable, the same "invisible is untappable" rule the menus keep.
 *
 * Order matters: BACK and the tabs sit above the rail and are tested first, so a
 * rail that happens to extend under them can never steal their taps.
 */
export function codexHitTest(layout: CodexLayout, x: number, y: number, railScroll = 0): CodexTarget | null {
  if (hitRect(layout.back, x, y)) return { kind: 'back' };
  for (let i = 0; i < layout.tabs.length; i++) {
    const rect = layout.tabs[i];
    if (rect && hitRect(rect, x, y)) return { kind: 'tab', index: i };
  }
  // Entries: only within the rail viewport, shifted by the scroll offset.
  if (!hitRect(layout.rail, x, y)) return null;
  for (let i = 0; i < layout.railEntries.length; i++) {
    const rect = layout.railEntries[i];
    if (!rect) continue;
    const shifted: Rect = { x: rect.x, y: rect.y - railScroll, width: rect.width, height: rect.height };
    if (hitRect(shifted, x, y)) return { kind: 'entry', index: i };
  }
  return null;
}

/** The codex's layout-registry id and anchor: it owns the screen. */
export const CODEX_ID = 'codex';

// ---------------------------------------------------------------------------
// Lobby reuse (GDD §2.10 point 2) — the same data, where the lobby answers a
// live question
// ---------------------------------------------------------------------------
//
// "The lobby reuses the same data … bot dossier on long-press/hover of a bot
// slot's name; hull description on the ship-class picker. Small, non-blocking,
// dismissible." These resolve a lobby row to its codex entry and hand back a
// compact hint — the same data the CODEX screen draws in full, trimmed to a
// tooltip. Pure lookups; the tooltip's gesture (long-press / hover) and its draw
// are the lobby view's and `src/main.ts`'s, off this seam.
//
// The keys line up by construction: a bot's personality id is the lowercased
// character name and the codex id is `bots-<id>` (`bots-rusty`); a hull's
// {@link ShipClass} value is the codex id's tail (`ship-interceptor`). Both
// resolvers are total — an unknown key returns null, so a future character with
// no codex entry yet simply shows no tooltip rather than crashing the row.

/** A compact codex reference for a lobby tooltip: a title, the one-line summary,
 *  and any difficulty/hull badges. Deliberately smaller than a full detail —
 *  "small, non-blocking, dismissible". */
export interface CodexHint {
  readonly title: string;
  readonly summary: string;
  readonly badges: readonly string[];
}

function hintFor(entry: CodexEntry | undefined): CodexHint | null {
  if (!entry) return null;
  const badges: string[] = [];
  if (entry.difficulty) badges.push(entry.difficulty);
  if (entry.hull) badges.push(entry.hull);
  return { title: entry.title, summary: entry.summary, badges };
}

/** The codex dossier for a lobby bot, by its personality id (or its display name
 *  — the two differ only in case). Null for a character with no entry. */
export function codexBotHint(data: CodexData, personality: string): CodexHint | null {
  const id = `bots-${personality.toLowerCase()}`;
  return hintFor(data.bots.entries.find((e) => e.id === id));
}

/** The codex hull description for the ship-class picker, by class. Null if the
 *  ships file has no entry for it. `shipClass` is a {@link ShipClass} value, e.g.
 *  `'interceptor'`. */
export function codexShipHint(data: CodexData, shipClass: string): CodexHint | null {
  return hintFor(data.ships.entries.find((e) => e.id === `ship-${shipClass}`));
}
