/**
 * src/ui/codex.ts — the CODEX reference screen. OWNER: Gameplay Engineer
 * (content/codex/ + this screen, brief c1-codex-screen; GDD §2.10).
 *
 * The optional main-menu reference a player consults voluntarily — "never a gate
 * before play" (GDD §2.10, verbatim). Five tabs (OBJECTIVE / BOTS / SHIPS /
 * SYSTEMS / STRATEGY) over the five `content/codex/*.json` files: a scrollable list of
 * entry titles on the left, the selected entry's detail on the right — its
 * summary, its body, the machine-checked `facts[]` (the numbers
 * `tests/codex/codex-constants.test.ts` pins to `src/sim/constants.ts`), any
 * difficulty/hull badges, and its cross-references. A BACK button leaves.
 *
 * Same three-piece discipline as every screen in this directory: a pure, DOM-free
 * model with its layout co-located, plus a thin Pixi view ({@link ./codex-view})
 * that draws exactly what this returns and decides nothing. Nothing here imports
 * PixiJS, so the whole screen unit-tests headless.
 *
 * **The data is handed in, not imported.** `content/codex/` lives outside `src/`
 * (it is regenerated by the codex pipeline, not compiled), so the model takes the
 * five parsed files as a value — `createCodex(normalizeCodex(files))` — exactly
 * as `lobbyModel` takes a `LobbyState`. Whoever boots the client
 * (`src/main.ts`) imports the JSON (Vite resolves it) and hands it over; the
 * tests load it off disk with `readFileSync`. So this file never reaches across
 * the compile boundary, and a malformed entry is normalised away here rather than
 * crashing a draw.
 *
 * **Scrolling lives in the view, not the model.** The entry rail (SYSTEMS has
 * fourteen entries) and a long body both scroll vertically; that offset is view
 * state. The one place the model must know about it is the hit test — a tap on a
 * scrolled rail lands on a different entry — so {@link codexHitTest} takes the
 * rail's scroll offset as a scalar and keeps the entry geometry pure and here,
 * rather than leaking it into the view.
 */

import type { Rect, Viewport } from '@platform/layout-registry';
import { rowHeight, valueChipHeight } from '../art/materials';
import type { FrameMetrics, PlateRole } from '../art/materials';
import { beamContent, beamPlate, gantryFrame } from './gantry';
import { hitRect } from './menu-geometry';
import type { Insets } from './menu-geometry';

// ---------------------------------------------------------------------------
// The five tabs
// ---------------------------------------------------------------------------

/** The five codex files, which are the five tabs, in screen order. */
export type CodexCategory = 'objective' | 'bots' | 'ships' | 'systems' | 'strategy';

/** One tab's identity. The layout, the view and the hit test all walk this same
 *  list, so a re-ordered tab strip can never mis-route a tap. */
export interface CodexTab {
  readonly id: CodexCategory;
  readonly label: string;
}

/**
 * The tabs, left to right — mapped one-to-one to the `content/codex/codex-*.json`
 * files, which is the contract a new section follows rather than special-cases.
 *
 * **OBJECTIVE is first, and that is a ruling (a0-34).** The codex's other four
 * tabs all describe how the game works to a reader who already knows what winning
 * is — the six STRATEGY entries are tactics for an unnamed goal — and no
 * player-facing string anywhere stated the win condition. The developer's call on
 * where the answer goes: *"id make it the first thing in the codex, and make sure
 * it's section is the first."* So it is a section of its own at the head of the
 * strip, not an entry bolted onto STRATEGY, and its first entry is the win
 * condition itself. The other four keep their contents and their relative order.
 */
export const CODEX_TABS: readonly CodexTab[] = [
  { id: 'objective', label: 'OBJECTIVE' },
  { id: 'bots', label: 'BOTS' },
  { id: 'ships', label: 'SHIPS' },
  { id: 'systems', label: 'SYSTEMS' },
  { id: 'strategy', label: 'STRATEGY' },
];

/** The screen's one heading, in Audiowide. */
export const CODEX_TITLE = 'CODEX';
/** The back control's label. */
export const CODEX_BACK_LABEL = 'BACK';

// ---------------------------------------------------------------------------
// The data — the parsed codex files, normalised into one typed shape
// ---------------------------------------------------------------------------

/** One machine-checked number from an entry's `facts[]`. `value` is the codex's
 *  claim; `unit` is its human unit ("HP", "s") or null for a bare count. The
 *  constant pointer that pins it to the sim is the pipeline's concern
 *  (`tests/codex/codex-constants.test.ts`), not the screen's, so it is dropped. */
export interface CodexFact {
  readonly label: string;
  readonly value: number;
  readonly unit: string | null;
}

/** One codex entry, normalised. Only the fields the screen draws survive the
 *  parse; `tags`, `category` and the fact `constant` pointers are pipeline
 *  metadata and are dropped here. */
export interface CodexEntry {
  readonly id: string;
  readonly title: string;
  readonly summary: string;
  readonly body: string;
  readonly facts: readonly CodexFact[];
  readonly seeAlso: readonly string[];
  /** A bot's difficulty tier ("Easy" / "Standard" / "Hard"), or null off the
   *  BOTS tab (and on the bots overview, which is nobody in particular). */
  readonly difficulty: string | null;
  /** A bot's hull, by lobby name, or null where the entry is not a single ship. */
  readonly hull: string | null;
}

/** One tab's worth of content: the file's title and its entries, in file order. */
export interface CodexSection {
  readonly category: CodexCategory;
  readonly title: string;
  readonly entries: readonly CodexEntry[];
}

/** All five sections, keyed by tab. Every tab is always present (an empty section
 *  for a file that failed to parse), so the screen never has to guard a tab. */
export type CodexData = Readonly<Record<CodexCategory, CodexSection>>;

/** The five parsed files, as `JSON.parse`/Vite hands them over — each `unknown`
 *  because a JSON import is not a typed thing until this module has vetted it. */
export type CodexRaw = Partial<Record<CodexCategory, unknown>>;

// --- Defensive coercion ----------------------------------------------------
//
// A codex file is player-facing fiction regenerated by a separate pipeline; a
// stray shape must never reach a draw as an `undefined.length`. Everything below
// coerces rather than trusts, and drops an entry that has no id/title/body — the
// three fields without which there is nothing to show.

function asString(value: unknown, fallback = ''): string {
  return typeof value === 'string' ? value : fallback;
}

function asStringOrNull(value: unknown): string | null {
  return typeof value === 'string' && value.length > 0 ? value : null;
}

function asStringArray(value: unknown): readonly string[] {
  if (!Array.isArray(value)) return [];
  return value.filter((v): v is string => typeof v === 'string');
}

function asFacts(value: unknown): readonly CodexFact[] {
  if (!Array.isArray(value)) return [];
  const facts: CodexFact[] = [];
  for (const raw of value) {
    if (raw === null || typeof raw !== 'object') continue;
    const f = raw as Record<string, unknown>;
    if (typeof f.value !== 'number') continue;
    facts.push({ label: asString(f.label), value: f.value, unit: asStringOrNull(f.unit) });
  }
  return facts;
}

function normalizeEntry(value: unknown): CodexEntry | null {
  if (value === null || typeof value !== 'object') return null;
  const e = value as Record<string, unknown>;
  const id = asString(e.id);
  const title = asString(e.title);
  const body = asString(e.body);
  if (id === '' || title === '' || body === '') return null;
  return {
    id,
    title,
    summary: asString(e.summary),
    body,
    facts: asFacts(e.facts),
    seeAlso: asStringArray(e.see_also),
    difficulty: asStringOrNull(e.difficulty),
    hull: asStringOrNull(e.hull),
  };
}

function normalizeSection(category: CodexCategory, value: unknown): CodexSection {
  const file = value !== null && typeof value === 'object' ? (value as Record<string, unknown>) : {};
  const rawEntries = Array.isArray(file.entries) ? file.entries : [];
  const entries: CodexEntry[] = [];
  for (const raw of rawEntries) {
    const entry = normalizeEntry(raw);
    if (entry) entries.push(entry);
  }
  return { category, title: asString(file.title), entries };
}

/** Vet the five parsed files into one typed {@link CodexData}. Total: a missing
 *  or malformed file becomes an empty section, and a malformed entry is dropped,
 *  so the screen is handed something it can always draw. */
export function normalizeCodex(raw: CodexRaw): CodexData {
  return {
    objective: normalizeSection('objective', raw.objective),
    bots: normalizeSection('bots', raw.bots),
    ships: normalizeSection('ships', raw.ships),
    systems: normalizeSection('systems', raw.systems),
    strategy: normalizeSection('strategy', raw.strategy),
  };
}

// ---------------------------------------------------------------------------
// The state
// ---------------------------------------------------------------------------

/** The whole screen, as one immutable value: the data, which tab is live, and
 *  which entry within it is selected (null only when a tab is empty). */
export interface CodexState {
  readonly data: CodexData;
  readonly activeTab: CodexCategory;
  readonly selectedId: string | null;
}

/** Open the codex on `tab` — OBJECTIVE by default, the first tab and now the
 *  first thing the codex says (a0-34) — with that tab's first entry selected. */
export function createCodex(data: CodexData, tab: CodexCategory = 'objective'): CodexState {
  return { data, activeTab: tab, selectedId: firstId(data[tab]) };
}

function firstId(section: CodexSection): string | null {
  return section.entries[0]?.id ?? null;
}

/**
 * Switch tabs, selecting the new tab's first entry. Identity-stable on a no-op
 * (tapping the live tab returns the same object) — the same stillness discipline
 * {@link ./lobby-flow} `withLobby` keeps, so a re-tap churns no state.
 */
export function selectCodexTab(state: CodexState, tab: CodexCategory): CodexState {
  if (tab === state.activeTab) return state;
  return { ...state, activeTab: tab, selectedId: firstId(state.data[tab]) };
}

/**
 * Select the entry at `index` within the active tab. Out-of-range indices and a
 * re-select of the live entry are no-ops that return the same object.
 */
export function selectCodexEntry(state: CodexState, index: number): CodexState {
  const entry = state.data[state.activeTab].entries[index];
  if (!entry || entry.id === state.selectedId) return state;
  return { ...state, selectedId: entry.id };
}

/** The entries of the active tab, in order — the list the rail draws. */
export function activeEntries(state: CodexState): readonly CodexEntry[] {
  return state.data[state.activeTab].entries;
}

/** The selected entry, or the tab's first as a fallback (a non-null selection
 *  that fell out of the data), or null for an empty tab. */
export function activeEntry(state: CodexState): CodexEntry | null {
  const entries = activeEntries(state);
  return entries.find((e) => e.id === state.selectedId) ?? entries[0] ?? null;
}

/** The selected entry's index in the active tab, or -1. */
export function activeEntryIndex(state: CodexState): number {
  return activeEntries(state).findIndex((e) => e.id === state.selectedId);
}

// ---------------------------------------------------------------------------
// The per-frame model
// ---------------------------------------------------------------------------

/**
 * One tab as the strip draws it.
 *
 * ---------------------------------------------------------------------------
 * TWO KINDS OF SELECTION, AND THEY MUST NOT LOOK THE SAME (u7-04)
 * ---------------------------------------------------------------------------
 * A tab and an entry are both "the selected one", and drawing them alike would
 * leave the screen saying the same thing twice in two places about two different
 * questions. They are marked differently on purpose:
 *
 *  - **The active TAB is a mode switch** — *which set of articles am I in?* — so
 *    it is marked by BRIGHTNESS: the selected chip's brighter metal and its Bone
 *    border, the same material the settings screen's engaged toggle wears.
 *  - **The selected ENTRY is a pointer** — *which article is in the pane beside
 *    me?* — so it is marked POSITIONALLY: a Bone bar down the row's leading edge,
 *    aiming at the pane, and the row rising from a surface (`inert`) to a raised
 *    plate (`secondary`). It is never the brightest thing on the screen.
 *
 * That also keeps the one-primary rule (`./gantry` `singlePrimary`) honest at the
 * plate level: the CODEX has no headline action at all, which is legal — zero
 * bright plates is a screen with nothing to press hardest, and a reference screen
 * is exactly that.
 */
export interface CodexTabView {
  readonly label: string;
  readonly active: boolean;
  /** Rest / hover / press, from the wiring layer's pointer routing. */
  readonly state: CodexPlateState;
}

/** One entry title as the rail draws it. */
export interface CodexEntryView {
  readonly title: string;
  readonly selected: boolean;
  readonly state: CodexPlateState;
}

/** A plate's interaction state. Mirrors `../art/materials` `PlateState`, restated
 *  here so the model does not make its consumers import the art module. */
export type CodexPlateState = 'rest' | 'hover' | 'press';

/**
 * The material an active/inactive TAB is drawn in — BRIGHTNESS, at chip size.
 *
 * The active tab is the `primary` chip: the brightest metal in the chip family
 * behind a Bone border, which is the set's existing word for *this is the current
 * one* (it is what the settings screen's engaged toggle wears). A `primary` CHIP
 * is not a second headline action — {@link ./gantry} `countPrimaries` takes the
 * roles of a screen's PLATES, and a chip's "primary" is a selected state — so the
 * CODEX still draws zero bright plates, which is what a reference screen should.
 */
export function codexTabPlate(tab: { readonly active: boolean }): PlateRole {
  return tab.active ? 'primary' : 'secondary';
}

/**
 * …and the material a rail ENTRY is drawn in — POSITION, at row size.
 *
 * An unselected row is an `inert` surface, held down on the panel exactly as a
 * settings row is. The selected one rises to a `secondary` plate and takes a Bone
 * bar down its leading edge (the view draws the bar). It is deliberately NOT the
 * `primary` chip the tab uses: the two are different questions — *which set am I
 * in* versus *which article is in the pane* — and answering both with the same
 * brightness would leave the screen saying one thing twice.
 */
export function codexEntryPlate(entry: { readonly selected: boolean }): PlateRole {
  return entry.selected ? 'secondary' : 'inert';
}

/** What the pointer is doing on the codex, each as a {@link codexTargetKey}. */
export interface CodexPointer {
  readonly hover?: string | null;
  readonly press?: string | null;
}

/** A rendered fact line — the value and unit already formatted ("15 HP"). */
export interface CodexFactView {
  readonly label: string;
  readonly value: string;
}

/** The detail pane for the selected entry. */
export interface CodexDetailView {
  readonly title: string;
  readonly summary: string;
  /** Difficulty / hull chips, in that order, present only when the entry has
   *  them (a bot). Empty for a systems or strategy entry. */
  readonly badges: readonly string[];
  readonly body: string;
  readonly facts: readonly CodexFactView[];
  readonly seeAlso: readonly string[];
}

/** The codex for one frame. The view draws exactly this. */
export interface CodexModel {
  readonly title: string;
  readonly backLabel: string;
  readonly sectionTitle: string;
  readonly tabs: readonly CodexTabView[];
  readonly entries: readonly CodexEntryView[];
  readonly detail: CodexDetailView | null;
  /** BACK's own plate state, from the same pointer routing as the tabs. */
  readonly backState: CodexPlateState;
}

/** Format a fact's value and unit for display: "15 HP", "10 s", or a bare "8". */
export function formatFactValue(fact: CodexFact): string {
  return fact.unit ? `${fact.value} ${fact.unit}` : `${fact.value}`;
}

/** Resolve `see_also` entry ids to their human titles, across every tab (a bot
 *  cross-links to a ship), dropping any id that names no entry. So the footer
 *  reads "Beta", never the raw "b2". */
function resolveSeeAlso(data: CodexData, ids: readonly string[]): readonly string[] {
  const titles: string[] = [];
  for (const id of ids) {
    for (const tab of CODEX_TABS) {
      const found = data[tab.id].entries.find((e) => e.id === id);
      if (found) {
        titles.push(found.title);
        break;
      }
    }
  }
  return titles;
}

function detailFor(entry: CodexEntry | null, data: CodexData): CodexDetailView | null {
  if (!entry) return null;
  const badges: string[] = [];
  if (entry.difficulty) badges.push(entry.difficulty);
  if (entry.hull) badges.push(entry.hull);
  return {
    title: entry.title,
    summary: entry.summary,
    badges,
    body: entry.body,
    facts: entry.facts.map((f) => ({ label: f.label, value: formatFactValue(f) })),
    seeAlso: resolveSeeAlso(data, entry.seeAlso),
  };
}

/** Build the frame model. Pure: the view draws exactly this and decides nothing.
 *  A press outranks a hover on the same plate — a finger that is down is not
 *  hovering — the rule every screen in this directory keeps. */
export function codexModel(state: CodexState, pointer: CodexPointer = {}): CodexModel {
  const selected = activeEntry(state);
  const hover = pointer.hover ?? null;
  const press = pointer.press ?? null;
  const stateFor = (key: string): CodexPlateState =>
    press === key ? 'press' : hover === key ? 'hover' : 'rest';
  return {
    title: CODEX_TITLE,
    backLabel: CODEX_BACK_LABEL,
    sectionTitle: state.data[state.activeTab].title,
    tabs: CODEX_TABS.map((t, i) => ({
      label: t.label,
      active: t.id === state.activeTab,
      state: stateFor(`tab:${i}`),
    })),
    entries: activeEntries(state).map((e, i) => ({
      title: e.title,
      selected: e.id === selected?.id,
      state: stateFor(`entry:${i}`),
    })),
    detail: detailFor(selected, state.data),
    backState: stateFor('back'),
  };
}

// ---------------------------------------------------------------------------
// Layout
//
// -- GANTRY / BONE (u7-04) --------------------------------------------------
// The CODEX is framed like the rest of the set now — a header beam, a footer
// beam, a page margin, one content band ({@link ./gantry} `gantryFrame`) — and it
// is the densest screen in the game: a tab row, a scrolling entry list and a long
// article, at 390px wide, in landscape and portrait-held.
//
// The rule that governs the density, and the reason this screen was not simply
// handed the title screen's treatment: **material must not cost legibility.** The
// reading pane is prose the player is actually reading, so the bevels, the rivets
// and the plate faces go on the CHROME AROUND it — the beams, the tab chips, the
// rail rows — and the article itself sits on bare Vacuum behind a hairline. A
// bevelled panel behind a paragraph is a texture under text, which is the one
// thing the frozen legibility rule (style-guide §9) will not buy at any price.
//
// The metrics that adapt, and what they were:
//
//  - `CODEX_TITLE_HEIGHT` (48) — the title band is the HEADER BEAM now.
//  - `CODEX_TAB_HEIGHT` / `_TOUCH` (44 / 52) — a tab is a `chip` plate, sized by
//    `valueChipHeight(metrics)`, which is floored at the 48px thumb minimum on
//    EVERY device rather than only when someone remembered to pass `isTouch`.
//    That is the brief's "its tabs must clear the 48px thumb floor", enforced by
//    the shared floor instead of by a second per-screen constant.
//  - `CODEX_ENTRY_HEIGHT` / `_TOUCH` (40 / 48) — a rail row is a settings-style
//    ROW, so it takes `rowHeight(metrics)`: also never under the thumb floor.
//  - `CODEX_ENTRY_GAP` (6) — the frame's own `rowGap`, so the rail breathes like
//    the settings screen rather than at a number of its own.
//  - `CODEX_BACK_WIDTH` (120 → 140) — BACK is a `compact` plate in the footer
//    beam now, at the same reference width the doors screen's BACK uses.
// ---------------------------------------------------------------------------

/** The entry rail's width band, at the 1280×720 reference. Wider than the
 *  pre-Gantry 132–260: a rail row is a PLATE now, with a selection bar down its
 *  leading edge and plate padding either side of the title, so the text column
 *  inside it is narrower than the row and the row has to grow to keep it. */
export const CODEX_RAIL_MIN = 220;
export const CODEX_RAIL_MAX = 360;
/** Fraction of the band's width the rail asks for before the min/max clamp. */
export const CODEX_RAIL_FRACTION = 0.34;
/** BACK's plate width in the footer beam, at the reference. The doors screen's. */
export const CODEX_BACK_WIDTH = 140;

export interface CodexLayoutOptions {
  readonly isTouch?: boolean;
  readonly insets?: Insets;
}

/**
 * The codex's rects. `railEntries` are the *unscrolled* positions of every entry
 * in the active tab, stacked from the top of `rail`; the view clips them to
 * `rail` and scrolls them, and {@link codexHitTest} shifts them by the same
 * offset. `detail` is the whole right pane; the body's own scroll is the view's.
 */
export interface CodexLayout {
  readonly content: Rect;
  /** The header beam — CODEX on the left, the section title on the right. */
  readonly header: Rect;
  /** The footer beam, which carries BACK and nothing else. */
  readonly footer: Rect;
  /** The heading's strip inside the header beam. */
  readonly title: Rect;
  readonly back: Rect;
  readonly tabs: readonly Rect[];
  readonly rail: Rect;
  readonly railEntries: readonly Rect[];
  readonly detail: Rect;
  readonly entryHeight: number;
  /** Gap between two rail rows. */
  readonly entryGap: number;
  readonly isTouch: boolean;
  readonly metrics: FrameMetrics;
}

/**
 * Lay the screen out for a viewport. Because a portrait phone is landscape-locked
 * (see `src/main.ts`), the logical viewport is always wide-and-short, so the rail
 * and detail sit side by side rather than stacking — the short height is what the
 * rail and body scroll to absorb.
 *
 * @param entryCount how many entries the active tab has — the rail lays out one
 *   rect per entry (the view scrolls the overflow).
 */
export function codexLayout(
  viewport: Viewport,
  entryCount: number,
  options: CodexLayoutOptions = {},
): CodexLayout {
  const isTouch = options.isTouch ?? false;
  const frame = gantryFrame(viewport, options.insets);
  const m = frame.metrics;

  // The header beam: the heading hard left, the section title hard right — the
  // SETTINGS screen's construction rather than the title screen's, because this
  // is a utility screen and its heading is what names it, not a wordmark.
  const title = beamContent(frame.header, m);
  const footerStrip = beamContent(frame.footer, m, 'footer');
  const back = beamPlate(
    footerStrip,
    m,
    'leading',
    Math.max(0, Math.min(Math.round(CODEX_BACK_WIDTH * m.plateScale), footerStrip.width)),
  );

  // The tab row, off the top of the band. A value chip's height, which is floored
  // at the thumb minimum on every device — the brief's one hard number here.
  const band = frame.band;
  const tabHeight = Math.max(0, Math.min(valueChipHeight(m), band.height));
  const tabs = tabStrip({ x: band.x, y: band.y, width: band.width, height: tabHeight }, m);

  const bodyTop = band.y + tabHeight + m.gutter;
  const bodyHeight = Math.max(0, band.y + band.height - bodyTop);

  const railWidth = clampRailWidth(band.width, m);
  const rail: Rect = { x: band.x, y: bodyTop, width: railWidth, height: bodyHeight };
  const detailX = rail.x + railWidth + m.gutter;
  const detail: Rect = {
    x: detailX,
    y: bodyTop,
    width: Math.max(0, band.x + band.width - detailX),
    height: bodyHeight,
  };

  const entryHeight = Math.max(0, Math.min(rowHeight(m), bodyHeight));
  const entryGap = m.rowGap;
  const railEntries: Rect[] = [];
  for (let i = 0; i < Math.max(0, entryCount); i++) {
    railEntries.push({
      x: rail.x,
      y: rail.y + i * (entryHeight + entryGap),
      width: rail.width,
      height: entryHeight,
    });
  }

  return {
    content: frame.content,
    header: frame.header,
    footer: frame.footer,
    title,
    back,
    tabs,
    rail,
    railEntries,
    detail,
    entryHeight,
    entryGap,
    isTouch,
    metrics: m,
  };
}

function clampRailWidth(bandWidth: number, m: FrameMetrics): number {
  const asked = bandWidth * CODEX_RAIL_FRACTION;
  const capped = Math.min(
    Math.round(CODEX_RAIL_MAX * m.scale),
    Math.max(Math.round(CODEX_RAIL_MIN * m.scale), asked),
  );
  // Never let the rail crowd out the detail on a genuinely tiny viewport: at most
  // half the band, so both panes always have a share — and the ARTICLE stays the
  // wider of the two at every size, because it is what the screen is for.
  return Math.max(0, Math.min(capped, bandWidth / 2));
}

/** One equal tab CHIP per {@link CODEX_TABS} entry across `band`, gap-separated,
 *  in that order. Chips, not plates: a tab is a mode switch, not an action. The
 *  strip divides by `CODEX_TABS.length` rather than by a literal, so the fifth tab
 *  (a0-34) narrowed every chip and needed no other change — a word that no longer
 *  fits its chip shrinks to fit rather than spilling (`./codex-view` `drawTab`). */
function tabStrip(band: Rect, m: FrameMetrics): Rect[] {
  const n = CODEX_TABS.length;
  const gap = m.rowGap;
  const width = Math.max(0, (band.width - (n - 1) * gap) / n);
  const rects: Rect[] = [];
  for (let i = 0; i < n; i++) {
    rects.push({ x: band.x + i * (width + gap), y: band.y, width, height: band.height });
  }
  return rects;
}

/** The total height every entry would occupy if the rail did not scroll — the
 *  view clamps its scroll offset to `max(0, this - rail.height)`. */
export function codexRailContentHeight(layout: CodexLayout): number {
  const n = layout.railEntries.length;
  if (n === 0) return 0;
  return n * layout.entryHeight + (n - 1) * layout.entryGap;
}

// ---------------------------------------------------------------------------
// Hit test
// ---------------------------------------------------------------------------

/** What a tap on the codex resolves to. */
export type CodexTarget =
  | { readonly kind: 'back' }
  | { readonly kind: 'tab'; readonly index: number }
  | { readonly kind: 'entry'; readonly index: number };

/**
 * The target a tap at `(x, y)` hits, or null. `railScroll` is how far the entry
 * rail has been scrolled down (view state, default 0): each entry's on-screen
 * rect is its layout rect shifted up by that offset, and a hit only counts if it
 * also falls inside the rail's clip rect — a title scrolled out of view is not
 * tappable, the same "invisible is untappable" rule the menus keep.
 *
 * Order matters: BACK and the tabs sit above the rail and are tested first, so a
 * rail that happens to extend under them can never steal their taps.
 */
export function codexHitTest(layout: CodexLayout, x: number, y: number, railScroll = 0): CodexTarget | null {
  if (hitRect(layout.back, x, y)) return { kind: 'back' };
  for (let i = 0; i < layout.tabs.length; i++) {
    const rect = layout.tabs[i];
    if (rect && hitRect(rect, x, y)) return { kind: 'tab', index: i };
  }
  // Entries: only within the rail viewport, shifted by the scroll offset.
  if (!hitRect(layout.rail, x, y)) return null;
  for (let i = 0; i < layout.railEntries.length; i++) {
    const rect = layout.railEntries[i];
    if (!rect) continue;
    const shifted: Rect = { x: rect.x, y: rect.y - railScroll, width: rect.width, height: rect.height };
    if (hitRect(shifted, x, y)) return { kind: 'entry', index: i };
  }
  return null;
}

/**
 * A stable string naming one codex control — `tab:2`, `entry:7`, `back`.
 *
 * The pointer layer needs to say "the finger is on THIS control" without holding
 * a rect, and both the hover cue (`src/main.ts`) and the plate's rest/hover/press
 * state ({@link codexModel}) ask the same question. Stating the key format once,
 * beside the target it names, is what keeps the two from drifting into two
 * spellings of one control — the same discipline `./lobby-geometry`
 * `entryTargetKey` keeps for the doors.
 */
export function codexTargetKey(target: CodexTarget | null): string | null {
  if (!target) return null;
  return target.kind === 'back' ? 'back' : `${target.kind}:${target.index}`;
}

/** The codex's layout-registry id and anchor: it owns the screen. */
export const CODEX_ID = 'codex';

// ---------------------------------------------------------------------------
// Lobby reuse (GDD §2.10 point 2) — the same data, where the lobby answers a
// live question
// ---------------------------------------------------------------------------
//
// "The lobby reuses the same data … bot dossier on long-press/hover of a bot
// slot's name; hull description on the ship-class picker. Small, non-blocking,
// dismissible." These resolve a lobby row to its codex entry and hand back a
// compact hint — the same data the CODEX screen draws in full, trimmed to a
// tooltip. Pure lookups; the tooltip's gesture (long-press / hover) and its draw
// are the lobby view's and `src/main.ts`'s, off this seam.
//
// The keys line up by construction: a bot's personality id is the lowercased
// character name and the codex id is `bots-<id>` (`bots-rusty`); a hull's
// {@link ShipClass} value is the codex id's tail (`ship-interceptor`). Both
// resolvers are total — an unknown key returns null, so a future character with
// no codex entry yet simply shows no tooltip rather than crashing the row.

/** A compact codex reference for a lobby tooltip: a title, the one-line summary,
 *  and any difficulty/hull badges. Deliberately smaller than a full detail —
 *  "small, non-blocking, dismissible". */
export interface CodexHint {
  readonly title: string;
  readonly summary: string;
  readonly badges: readonly string[];
}

function hintFor(entry: CodexEntry | undefined): CodexHint | null {
  if (!entry) return null;
  const badges: string[] = [];
  if (entry.difficulty) badges.push(entry.difficulty);
  if (entry.hull) badges.push(entry.hull);
  return { title: entry.title, summary: entry.summary, badges };
}

/** The codex dossier for a lobby bot, by its personality id (or its display name
 *  — the two differ only in case). Null for a character with no entry. */
export function codexBotHint(data: CodexData, personality: string): CodexHint | null {
  const id = `bots-${personality.toLowerCase()}`;
  return hintFor(data.bots.entries.find((e) => e.id === id));
}

/** The codex hull description for the ship-class picker, by class. Null if the
 *  ships file has no entry for it. `shipClass` is a {@link ShipClass} value, e.g.
 *  `'interceptor'`. */
export function codexShipHint(data: CodexData, shipClass: string): CodexHint | null {
  return hintFor(data.ships.entries.find((e) => e.id === `ship-${shipClass}`));
}
