/**
 * evidence/a0-127-three-changes-with-eyes/shoot-picker.mjs — MAP SELECT, six
 * arenas, at true size. OWNER: QA Manager (a0-127).
 *
 * a0-124 rebuilt the card previews so they are *"showing the ores, empty stations
 * locations, the nebulas and stars in the back"*, generated by building the map's
 * own world rather than by drawing a dot list. The brief this evidence serves
 * warned that accuracy which turns to mush at 240×114 is worse than the honest
 * dots it replaced — so the verdict is taken at TRUE SIZE and nowhere else:
 * `<profile>-map-select.png` is 1 image pixel per device pixel of a dpr-2 phone,
 * which is what a player's eye receives. The 4× card crops exist only to show a
 * reader the detail being described; no verdict is read off them.
 *
 * The screen is reached the way a player reaches it — real taps at the points the
 * client itself reports drawing its controls at, PLAY → PLAY SOLO → the lobby's
 * arena card — never a seam that just sets the state.
 */
import { chromium } from 'playwright';
import { writeFileSync } from 'node:fs';
import { join } from 'node:path';
import { CROPS, DESKTOP, PHONE, SHOTS, bootMenu, crop, elements, frame, note, pageOptions, park, settle, shotPath, stamp, writeCrop } from './lib.mjs';

const browser = await chromium.launch();
const readback = [];

for (const profile of [PHONE, DESKTOP]) {
  const page = await browser.newPage(pageOptions(profile));
  page.on('pageerror', (e) => console.log('  [pageerror]', e.message));
  const press = async (p) => {
    if (profile.touch) await page.touchscreen.tap(p.x, p.y);
    else await page.mouse.click(p.x, p.y);
    await settle(page, 10);
  };

  await bootMenu(page);
  const play = await page.evaluate(() => {
    const c = window.__mainMenu.controls.find((k) => k.kind === 'play');
    return c ? { ...c.physicalCenter } : null;
  });
  await press(play);
  const solo = await page.evaluate(() => {
    const c = (window.__onlineMenu?.doorControls ?? []).find((k) => k.kind === 'solo');
    return c ? { ...c.physicalCenter } : null;
  });
  await press(solo);
  await page.waitForFunction(() => typeof window.__lobby?.rush === 'function', undefined, { timeout: 30_000 });
  const card = await page.evaluate(() => (window.__lobby?.mapCardControl ? { ...window.__lobby.mapCardControl.physicalCenter } : null));
  await press(card);
  await page.waitForFunction(() => window.__lobby?.screen === 'map-select' && window.__lobby.mapCards.length === 6, undefined, { timeout: 30_000 });
  await park(page);

  const name = `${profile.id}-map-select`;
  await frame(page, name);

  const state = await page.evaluate(() => ({
    screen: window.__lobby.screen,
    order: [...window.__lobby.mapOrder],
    selected: window.__lobby.selectedMapId,
    veteran: window.__lobby.veteranMapId,
    cards: window.__lobby.mapCards.map((c) => ({ ...c })),
  }));
  const els = await elements(page);
  readback.push({ name, profile: profile.id, stamp: await stamp(page), ...state, elements: els });

  // One 4× crop per card — for a reader to see the detail the attestation
  // describes. The verdict is taken on the frame above, not on these.
  state.cards.forEach((c, i) => {
    const id = state.order[i] ?? `card${i}`;
    writeCrop(
      `${profile.id}-card-${id}-4x`,
      crop(shotPath(name), {
        x: Math.round(c.x * profile.dpr),
        y: Math.round(c.y * profile.dpr),
        w: Math.round(c.width * profile.dpr),
        h: Math.round(c.height * profile.dpr),
        scale: 4,
      }),
    );
  });
  console.log(`${name}: ${state.cards.length} cards, order ${state.order.join(',')}, selected ${state.selected}`);
  console.log(`  elements: ${els.map((e) => e.id).join(', ')}`);
  await page.close();
}

note('map-select-readback', readback);
await browser.close();
