/**
 * evidence/b2-03-join-the-assault.ts — **the two frames the brief asks for.**
 * OWNER: Bot Engineer (b2-03; `docs/team-bots-plan.md` Stage 4).
 *
 * A Teams match, captured, and the control frame beside it:
 *
 *  - **THE JOIN.** A teammate opens an attack on an enemy home and says so on
 *    the channel. A bot in range breaks off what it was doing, flies across the
 *    board, and presses the same siege.
 *  - **THE LADDER.** The identical callout, at the identical instant, while that
 *    bot's *own* home is under attack. It stays home. That is the frame which
 *    proves the ladder is still selfish-first — **my home outranks yours, and my
 *    home outranks your raid** — and it is the half that keeps this from becoming
 *    a bot that abandons its own core to be useful somewhere else.
 *
 * Both runs are the **same seed, the same cast, the same board, the same tick**.
 * The only difference between them is one number: whether slot 0's own station
 * has taken damage inside the alarm window. Everything printed is read out of the
 * running sim and the bot's own `Brain`; nothing here writes to `src/`.
 *
 * Deliberately shaped as the twin of `./a0-10-defend-an-ally.ts`, because the
 * developer's ask was one sentence with two halves and the evidence should read
 * that way too.
 *
 * Re-run:  npx vite-node evidence/b2-03-join-the-assault.ts
 * Writes:  evidence/b2-03-join-the-assault.json
 */

import { writeFileSync } from 'node:fs';
import { ShipClass } from '../src/shared/types';
import type { PlayerId, Vec2 } from '../src/shared/types';
import { SPAWN_PROTECTION_S, TICK_DT, createWorld, step, type World } from '../src/sim';
import { ASSAULT_JOIN_RANGE, botInputs, botLobby, createBots, fillEmptySlots } from '../src/bots';

const ME = 0;
const ALLY = 1;
const FOE = 2;
const FOE2 = 3;
/** 2v2: slots 0+1 against 2+3. */
const SIDES = [0, 0, 1, 1] as const;
/** Sable honours a called target (`opportunism` 0.9 — the plan's own dial for
 *  this, §4.5); Vulture is the teammate that opens the raid. */
const CAST = ['sable', 'vulture', 'warden', 'foreman'] as const;

const SEED = 20260809;
const SECONDS = 40;

const dist = (a: Vec2, b: Vec2): number => Math.hypot(a.x - b.x, a.y - b.y);

/**
 * The board. Slot 0 sits out at a rock field 900 units from the home its
 * teammate is hitting — inside Sable's join reach (1000 × (0.55 + 0.9) = 1450)
 * and far enough that flying there is a visible, costly decision rather than a
 * step. Slot 1 is parked on the objective, which is what makes this a raid in
 * progress rather than a rumour.
 */
function board(): World {
  const seats = fillEmptySlots([], 4, [...CAST], [...SIDES]);
  const world = createWorld({ seed: SEED, players: botLobby(seats), bounds: { width: 6000, height: 6000 } });
  world.time = SPAWN_PROTECTION_S + 5;

  place(world, ME, { x: 3000, y: 3000 }, { x: 3000, y: 3300 });
  place(world, ALLY, { x: 3060, y: 2100 }, { x: 3000, y: 3600 });
  place(world, FOE, { x: 3000, y: 1950 }, { x: 3000, y: 2100 });
  place(world, FOE2, { x: 900, y: 5600 }, { x: 900, y: 5600 });
  return world;
}

function place(world: World, id: PlayerId, ship: Vec2, home: Vec2): void {
  const s = world.ships.find((x) => x.id === id)!;
  s.pos = { ...ship };
  s.vel = { x: 0, y: 0 };
  s.home = { ...home };
  s.hull = s.maxHull;
  s.cargo = 0;
  s.spawnProtect = 0;
  const p = world.stations.find((x) => x.owner === id)!;
  p.pos = { ...home };
  p.coreHp = p.maxCoreHp;
  p.spawnProtect = 0;
  p.sinceDamage = 999;
}

interface Sample {
  readonly t: number;
  readonly behavior: string;
  readonly joining: PlayerId;
  readonly toObjective: number;
  readonly toOwnHome: number;
  readonly pushCallsHeard: number;
  readonly ownAlarm: boolean;
}

/**
 * Run the board and — when `ownHomeToo` — hold slot 0's own home under fire at
 * the same time, by writing `sinceDamage` back after each step, which is exactly
 * what an attacker who does not leave produces.
 *
 * Nothing forces the `push` call: slot 1 opens the raid on its own and announces
 * it through the ordinary attack verbs. That is the point — the callout traffic
 * counted below is traffic the cast generated by playing.
 */
function run(ownHomeToo: boolean): { samples: Sample[]; summary: Record<string, unknown> } {
  const seats = fillEmptySlots([], 4, [...CAST], [...SIDES]);
  const world = board();
  const bots = createBots(seats, { seed: SEED });
  const me = bots.find((b) => b.seat.id === ME)!;
  const objective = world.stations.find((p) => p.owner === FOE)!.pos;
  const ownHome = world.stations.find((p) => p.owner === ME)!.pos;

  const samples: Sample[] = [];
  const behaviors = new Map<string, number>();
  let closest = Number.POSITIVE_INFINITY;
  let ticks = 0;

  while (world.time < SPAWN_PROTECTION_S + 5 + SECONDS) {
    step(world, botInputs(world, bots, TICK_DT), TICK_DT);
    if (ownHomeToo) world.stations.find((p) => p.owner === ME)!.sinceDamage = 0;

    const ship = world.ships.find((s) => s.id === ME)!;
    const toObjective = dist(ship.pos, objective);
    closest = Math.min(closest, toObjective);
    behaviors.set(me.brain.lastBehavior, (behaviors.get(me.brain.lastBehavior) ?? 0) + 1);
    ticks++;

    // One sample a second: enough to read the flight, short enough to eyeball.
    if (ticks % 60 === 0) {
      samples.push({
        t: +(ticks / 60).toFixed(1),
        behavior: me.brain.lastBehavior,
        joining: me.brain.allyAssault.target,
        toObjective: Math.round(toObjective),
        toOwnHome: Math.round(dist(ship.pos, ownHome)),
        pushCallsHeard: (me.brain.radio?.calls ?? []).filter((c) => c.kind === 'push').length,
        ownAlarm: ownHomeToo,
      });
    }
  }

  return {
    samples,
    summary: {
      closestApproachToObjective: Math.round(closest),
      startedAtFromObjective: 900,
      behaviourTickShare: Object.fromEntries(
        [...behaviors].sort((a, b) => b[1] - a[1]).map(([k, v]) => [k, `${((100 * v) / ticks).toFixed(1)}%`]),
      ),
      pushCallsOnTheChannel: (me.brain.radio?.calls ?? []).filter((c) => c.kind === 'push').length,
      calloutsOnTheChannel: me.brain.radio?.calls.length ?? 0,
    },
  };
}

const joined = run(false);
const held = run(true);

const out = {
  what: "b2-03 — a bot joins its teammate's attack, and stays home when its own core is burning",
  ask: 'the developer, 2026-08-07: "…and equally should try to attack when team mates go on offensive"',
  plan: 'docs/team-bots-plan.md Stage 4 (focus fire); the defensive half is a0-10 / Stage 2',
  fixture: {
    seed: SEED,
    lineup: 'TEAMS 2v2 — sable + vulture vs warden + foreman',
    observer: "slot 0 (Sable), starting 900 units from the home its teammate is hitting",
    assaultJoinRange: `ASSAULT_JOIN_RANGE ${ASSAULT_JOIN_RANGE} × (0.55 + opportunism 0.9) = ${ASSAULT_JOIN_RANGE * 1.45}`,
    note: "both runs are the same seed, cast, board and tick; the ONLY difference is whether slot 0's own home is also taking fire",
    unscripted: 'no callout is injected — slot 1 opens the raid and announces it through the ordinary attack verbs',
  },
  frame1_theJoin: {
    reading: 'my teammate called a push on that home, my home is quiet — I go',
    ...joined.summary,
    trace: joined.samples,
  },
  frame2_theLadder: {
    reading: 'the same callout, and my own core is burning too — I stay',
    ...held.summary,
    trace: held.samples,
  },
  verdict: {
    joinedClosed: `${900 - (joined.summary.closestApproachToObjective as number)} units closed toward the objective`,
    heldClosed: `${900 - (held.summary.closestApproachToObjective as number)} units closed`,
    ladderIntact:
      (held.summary.behaviourTickShare as Record<string, string>)['join-assault'] === undefined,
    theCallWasUnscripted: (joined.summary.pushCallsOnTheChannel as number) > 0,
  },
};

writeFileSync(new URL('./b2-03-join-the-assault.json', import.meta.url), `${JSON.stringify(out, null, 2)}\n`);
console.log(JSON.stringify(out.verdict, null, 2));
console.log('frame 1:', out.frame1_theJoin.behaviourTickShare, 'closest', out.frame1_theJoin.closestApproachToObjective);
console.log('frame 2:', out.frame2_theLadder.behaviourTickShare, 'closest', out.frame2_theLadder.closestApproachToObjective);
